import { ThemeMode } from '../../types';

export const getProjectsStyles = (mode: ThemeMode, accentPrimary: string, accentGlow: string) => ({
  section: {
    py: { xs: 10, md: 14 },
    px: { xs: 3, md: 8 },
    borderTop: '1px solid',
    borderColor: 'divider',
  },
  sectionLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 1.5,
  },
  sectionTitle: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    mb: 1,
  },
  sectionSub: {
    fontSize: '0.95rem',
    color: 'text.secondary',
    mb: 6,
    maxWidth: '600px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
    gap: { xs: 3, md: 4 },
  },
  card: {
    p: { xs: 2.5, md: 4.5 },
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: mode === 'aurora' ? '20px' : mode === 'chalk' ? '8px' : '4px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2.5,
    position: 'relative' as const,
    overflow: 'hidden',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    '&:hover': {
      borderColor: accentPrimary,
      boxShadow: `0 0 30px ${accentGlow}`,
      transform: 'translateY(-4px)',
    },
  },
  cardGlow: {
    position: 'absolute' as const,
    right: -50,
    top: -50,
    width: 120,
    height: 120,
    background: accentGlow,
    borderRadius: '50%',
    filter: 'blur(40px)',
    opacity: 0,
    transition: 'opacity 0.3s ease',
    pointerEvents: 'none' as const,
  },
  title: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 700,
    fontSize: '1.3rem',
    letterSpacing: '-0.01em',
    position: 'relative' as const,
    zIndex: 1,
  },
  description: {
    color: 'text.secondary',
    fontSize: '0.95rem',
    lineHeight: 1.6,
    position: 'relative' as const,
    zIndex: 1,
  },
  technologiesLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.7rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mt: 1,
    mb: 1,
    position: 'relative' as const,
    zIndex: 1,
  },
  tagContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 0.75,
    position: 'relative' as const,
    zIndex: 1,
  },
  tag: {
    px: 2,
    py: 0.75,
    border: `1px solid ${accentPrimary}`,
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    fontSize: '0.75rem',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 600,
    color: accentPrimary,
    backgroundColor: 'transparent',
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: accentPrimary,
      color: 'background.paper',
    },
  },
  bulletsLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.7rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mt: 1.5,
    mb: 1.5,
    position: 'relative' as const,
    zIndex: 1,
  },
  bullet: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1.5,
    mb: 1,
    color: 'text.secondary',
    fontWeight: 300,
    fontSize: '0.85rem',
    lineHeight: 1.6,
    position: 'relative' as const,
    zIndex: 1,
  },
  bulletDot: {
    width: 3,
    height: 3,
    borderRadius: '50%',
    background: accentPrimary,
    mt: '8px',
    flexShrink: 0,
  },
});
