import { ThemeMode } from '../../types';

export const getEducationStyles = (mode: ThemeMode, accentPrimary: string, accentGlow: string) => ({
  section: {
    py: { xs: 10, md: 14 },
    px: { xs: 3, md: 8 },
    borderTop: '1px solid',
    borderColor: 'divider',
  },
  sectionLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 1.5,
  },
  sectionTitle: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    mb: 6,
  },
  card: {
    p: { xs: 4, md: 6 },
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: mode === 'aurora' ? '20px' : mode === 'chalk' ? '4px' : '2px',
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' } as const,
    alignItems: { xs: 'flex-start', md: 'center' },
    gap: 4,
    position: 'relative' as const,
    overflow: 'hidden',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      borderColor: accentPrimary,
      boxShadow: `0 0 40px ${accentGlow}`,
    },
  },
  degreeLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.7rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 0.75,
  },
  degree: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 700,
    fontSize: '1.4rem',
    letterSpacing: '-0.01em',
    mb: 0.5,
  },
  institution: {
    color: 'text.secondary',
    fontWeight: 400,
  },
  yearBadge: {
    ml: { xs: 0, md: 'auto' },
    px: 3,
    py: 1.5,
    border: '1px solid',
    borderColor: accentPrimary,
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    color: accentPrimary,
    fontFamily: '"Syne", sans-serif',
    fontWeight: 700,
    fontSize: '1.1rem',
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    boxShadow: `0 0 20px ${accentGlow}`,
  },
  bgText: {
    position: 'absolute' as const,
    right: -20,
    bottom: -30,
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    fontSize: '8rem',
    color: accentPrimary,
    opacity: 0.03,
    lineHeight: 1,
    pointerEvents: 'none' as const,
    userSelect: 'none' as const,
  },
});
