import { ThemeMode } from '../../types';

export const getHeroStyles = (mode: ThemeMode, accentPrimary: string, accentGlow: string) => ({
  section: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    position: 'relative' as const,
    overflow: 'hidden',
    px: { xs: 3, md: 8 },
    pt: 12,
  },
  backgroundOrb: {
    position: 'absolute' as const,
    borderRadius: '50%',
    filter: 'blur(80px)',
    pointerEvents: 'none' as const,
    background: accentGlow,
    opacity: mode === 'chalk' ? 0.4 : 0.6,
  },
  eyebrow: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.8rem',
    letterSpacing: '0.15em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 2,
    opacity: 0,
    animation: 'fadeUp 0.6s ease 0.1s forwards',
  },
  headline: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    lineHeight: 1.0,
    letterSpacing: '-0.04em',
    mb: 3,
    opacity: 0,
    animation: 'fadeUp 0.7s ease 0.25s forwards',
  },
  subline: {
    fontWeight: 300,
    maxWidth: 540,
    lineHeight: 1.7,
    mb: 5,
    opacity: 0,
    animation: 'fadeUp 0.7s ease 0.4s forwards',
  },
  ctaRow: {
    display: 'flex',
    gap: 2,
    flexWrap: 'wrap' as const,
    opacity: 0,
    animation: 'fadeUp 0.7s ease 0.55s forwards',
  },
  primaryCta: {
    background: accentPrimary,
    color: mode === 'chalk' ? '#fff' : '#0A0A0A',
    px: 4,
    py: 1.5,
    fontFamily: '"Syne", sans-serif',
    fontWeight: 700,
    fontSize: '0.9rem',
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    '&:hover': { opacity: 0.88, background: accentPrimary },
  },
  secondaryCta: {
    border: `1px solid`,
    borderColor: 'divider',
    px: 4,
    py: 1.5,
    fontFamily: '"Syne", sans-serif',
    fontWeight: 600,
    fontSize: '0.9rem',
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    color: 'text.primary',
    '&:hover': { borderColor: accentPrimary },
  },
  decorGrid: {
    position: 'absolute' as const,
    right: 0,
    top: 0,
    width: { xs: '30%', md: '45%' },
    height: '100%',
    opacity: mode === 'chalk' ? 0.04 : 0.035,
    backgroundImage: `repeating-linear-gradient(0deg, currentColor, currentColor 1px, transparent 1px, transparent 60px),
      repeating-linear-gradient(90deg, currentColor, currentColor 1px, transparent 1px, transparent 60px)`,
    pointerEvents: 'none' as const,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.72rem',
    px: 1.5,
    py: 0.6,
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    border: `1px solid`,
    borderColor: 'divider',
    color: 'text.secondary',
    opacity: 0,
    animation: 'fadeUp 0.7s ease 0.7s forwards',
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: '#34D399',
    display: 'inline-block',
    animation: 'pulse 2s infinite',
  },
});
