import { ThemeMode } from '../../types';

export const getSkillsStyles = (mode: ThemeMode, accentPrimary: string, accentGlow: string) => ({
  section: {
    py: { xs: 10, md: 14 },
    px: { xs: 3, md: 8 },
    position: 'relative' as const,
    overflow: 'hidden',
  },
  sectionLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 1.5,
  },
  sectionTitle: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    mb: 1,
  },
  sectionSub: {
    color: 'text.secondary',
    mb: 8,
    maxWidth: 480,
    fontWeight: 300,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr', md: '1fr 1fr 1fr' },
    gap: 2,
  },
  card: {
    p: 3.5,
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: mode === 'aurora' ? '16px' : mode === 'chalk' ? '4px' : '2px',
    background: 'background.paper',
    position: 'relative' as const,
    overflow: 'hidden',
    cursor: 'default',
    transition: 'all 0.3s ease',
    '&:hover': {
      borderColor: accentPrimary,
      transform: 'translateY(-3px)',
      boxShadow: `0 12px 40px ${accentGlow}`,
    },
  },
  cardIcon: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '1.4rem',
    color: accentPrimary,
    mb: 2,
    display: 'block',
  },
  cardLabel: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 600,
    fontSize: '0.95rem',
    mb: 2,
  },
  chip: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.68rem',
    height: 26,
    borderRadius: mode === 'aurora' ? '999px' : '2px',
    border: '1px solid',
    borderColor: 'divider',
    color: 'text.secondary',
    background: 'transparent',
    transition: 'all 0.2s ease',
    '&:hover': {
      borderColor: accentPrimary,
      color: accentPrimary,
      background: 'transparent',
    },
  },
  cardGlow: {
    position: 'absolute' as const,
    top: -20,
    right: -20,
    width: 80,
    height: 80,
    borderRadius: '50%',
    background: accentGlow,
    filter: 'blur(20px)',
    pointerEvents: 'none' as const,
    opacity: 0,
    transition: 'opacity 0.3s ease',
  },
});
