import { ThemeMode } from '../../types';

export const getContactStyles = (mode: ThemeMode, accentPrimary: string, accentSecondary: string, accentGlow: string) => ({
  section: {
    py: { xs: 12, md: 18 },
    px: { xs: 3, md: 8 },
    borderTop: '1px solid',
    borderColor: 'divider',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  innerGlow: {
    position: 'absolute' as const,
    bottom: -200,
    left: '50%',
    transform: 'translateX(-50%)',
    width: { xs: 400, md: 600 },
    height: { xs: 300, md: 400 },
    borderRadius: '50%',
    background: accentGlow,
    filter: 'blur(100px)',
    pointerEvents: 'none' as const,
  },
  sectionLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 1.5,
  },
  headline: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    letterSpacing: '-0.04em',
    lineHeight: 1.05,
    mb: 3,
  },
  sub: {
    color: 'text.secondary',
    fontWeight: 300,
    mb: 6,
    maxWidth: 440,
    lineHeight: 1.7,
  },
  contactRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 2,
  },
  contactCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    px: 3,
    py: 2,
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: mode === 'aurora' ? '12px' : '2px',
    textDecoration: 'none',
    color: 'text.primary',
    transition: 'all 0.25s ease',
    '&:hover': {
      borderColor: accentPrimary,
      color: accentPrimary,
      boxShadow: `0 4px 20px ${accentGlow}`,
      transform: 'translateY(-2px)',
    },
  },
  contactIcon: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '1rem',
    color: accentSecondary,
  },
  contactLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.72rem',
    color: 'text.secondary',
    display: 'block',
  },
  contactValue: {
    fontFamily: '"DM Sans", sans-serif',
    fontWeight: 500,
    fontSize: '0.9rem',
  },
  footer: {
    mt: 14,
    pt: 4,
    borderTop: '1px solid',
    borderColor: 'divider',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    gap: 2,
  },
  footerLogo: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    fontSize: '1.1rem',
    color: accentPrimary,
  },
  footerNote: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.68rem',
    color: 'text.secondary',
    letterSpacing: '0.05em',
  },
});
