import { ThemeMode } from '../../types';

export const getExperienceStyles = (_mode: ThemeMode, accentPrimary: string, accentSecondary: string, accentGlow: string) => ({
  section: {
    py: { xs: 10, md: 14 },
    px: { xs: 3, md: 8 },
    position: 'relative' as const,
  },
  sectionLabel: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.75rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    color: accentPrimary,
    mb: 1.5,
  },
  sectionTitle: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    mb: 8,
  },
  timeline: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 0,
    position: 'relative' as const,
  },
  timelineLine: {
    position: 'absolute' as const,
    left: { xs: 0, md: 0 },
    top: 0,
    bottom: 0,
    width: 1,
    background: `linear-gradient(to bottom, ${accentPrimary}, ${accentSecondary}, transparent)`,
    opacity: 0.3,
    ml: { xs: 0, md: 0 },
  },
  entry: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '200px 1fr' },
    gap: { xs: 2, md: 6 },
    pl: { xs: 3, md: 0 },
    pb: 8,
    position: 'relative' as const,
  },
  dot: {
    position: 'absolute' as const,
    left: { xs: -5, md: -5 },
    top: 6,
    width: 10,
    height: 10,
    borderRadius: '50%',
    background: accentPrimary,
    boxShadow: `0 0 12px ${accentGlow}`,
    zIndex: 1,
  },
  periodBlock: {
    textAlign: { xs: 'left', md: 'right' } as const,
  },
  period: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.72rem',
    color: accentPrimary,
    display: 'block',
    mb: 0.5,
  },
  location: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.68rem',
    color: 'text.secondary',
  },
  role: {
    fontFamily: '"Syne", sans-serif',
    fontWeight: 700,
    fontSize: '1.3rem',
    mb: 0.4,
    letterSpacing: '-0.01em',
  },
  company: {
    fontFamily: '"DM Sans", sans-serif',
    fontWeight: 500,
    color: 'text.secondary',
    mb: 2.5,
    fontSize: '0.9rem',
  },
  bullet: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1.5,
    mb: 1.2,
    color: 'text.secondary',
    fontWeight: 300,
    fontSize: '0.92rem',
    lineHeight: 1.65,
  },
  bulletDot: {
    width: 4,
    height: 4,
    borderRadius: '50%',
    background: accentPrimary,
    mt: '9px',
    flexShrink: 0,
  },
});
